Repository brabbuss/refactor-tractor, pull requests merged in 2020-11, with the labels that each got.

#55 Feature/inputs and posts es
  src/DOM-loader.js
  src/classes/User.js
  src/scripts.js
Labels: Adjustment, bug, enhancement

#65 Refactor/scripts class tdd
  src/classes/HydrationRepository.js
  src/classes/User.js
  src/scripts.js
Labels: Adjustment, bug

#69 Feature/clean up forms wave audit
  src/DOM-loader.js
  src/classes/User.js
  src/css/_variables.scss
  src/css/index.scss
  src/css/styles.scss
  src/index.html
  src/scripts.js
  src/styles.css
Labels: Accessibility, Adjustment, enhancement
